sw_xss = [
  ['innerhtml', 'a', 0],
  ['script', 'a', 0],
  ['svg', 'a', 0],
  ['contenteditable', 'a', 0],
  ['x', 'a', 0],
  ['src', 'a', 0],
  ['iframe', 'a', 0],
  ['javascript', 'a', 0],
  ['embed', 'a', 0],
  ['math', 'a', 0],
  ['brute', 'a', 0],
  ['href', 'a', 0],
  ['form', 'a', 0],
  ['action', 'a', 0],
  ['input', 'a', 0],
  ['type', 'a', 0],
  ['submit', 'a', 0],
  ['isindex', 'a', 0],
  ['value', 'a', 0],
  ['button', 'a', 0],
  ['formaction', 'a', 0],
  ['srcdoc', 'a', 0],
  ['xlink', 'a', 0],
  ['img', 'a', 0],
  ['xmlns', 'a', 0],
  ['link', 'a', 0],
  ['base', 'a', 0],
  ['style', 'a', 0],
  ['marquee', 'a', 0],
  ['audio', 'a', 0],
  ['video', 'a', 0],
  ['keygen', 'a', 0],
  ['autofocus', 'a', 0],
  ['select', 'a', 0],
  ['option', 'a', 0],
  ['menu', 'a', 0],
  ['contextmenu', 'a', 0],
  ['textarea', 'a', 0],
  ['source', 'a', 0],
  ['meta', 'a', 0],
  ['object', 'a', 0],
  ['html', 'a', 0],
  ['target', 'a', 0],
  ['card ', 'a', 0],
  ['onevent', 'a', 0],
  ['animate', 'a', 0],
  ['handler', 'a', 0],
  ['feimage', 'a', 0],
  ['table', 'a', 0],
  ['background', 'a', 0],
  ['frameset', 'a', 0],
  ['div', 'a', 0],
  ['allowscriptaccess', 'a', 0],
  ###############################
  ['onload', 'b',0],
  ['onmouseover', 'b',0],
  ['onsubmit', 'b',0],
  ['onfocus', 'b',0],
  ['onblur', 'b',0],
  ['onclick', 'b',0],
  ['oncopy', 'b',0],
  ['oncontextmenu', 'b',0],
  ['oncut', 'b',0],
  ['ondblclick', 'b',0],
  ['ondrag', 'b',0],
  ['oninput', 'b',0],
  ['onkeydown', 'b',0],
  ['onkeypress', 'b',0],
  ['onkeyup', 'b',0],
  ['onmousedown', 'b',0],
  ['onmousemove', 'b',0],
  ['onmouseout', 'b',0],
  ['onmouseup', 'b',0],
  ['onpaste', 'b',0],
  ['ontouchstart', 'b',0],
  ['ontouchend', 'b',0],
  ['ontouchmove', 'b',0],
  ['ontouchcancel', 'b',0],
  ['onorientationchange', 'b',0],
  ['onerror', 'b',0],
  ['onpageshow', 'b',0],
  ['onhashchange', 'b',0],
  ['onscroll', 'b',0],
  ['onresize', 'b',0],
  ['onhelp', 'b',0],
  ['onstart', 'b',0],
  ['onloadstart', 'b',0],
  ['onchange', 'b',0],
  ['onshow', 'b',0],
  ['oneonerrorrror', 'b',0],
  ['ontoggle', 'b',0],
  ['onafterscriptexecute', 'b',0],
  ['onbeforescriptexecute', 'b',0],
  ['onfinish', 'b',0],
  ['expression', 'b',0],
  ['onbeforeload', 'b',0],
  ['onbeforeunload', 'b',0],
  ['onformchange', 'b',0],
  ['vbscript', 'b',0],
  ##########################
  ['eval', 'c',0],
  ['find', 'c',0],
  ['top', 'c',0],
  ['source', 'c',0],
  ['tostring', 'c',0],
  ['url', 'c',0],
  ['slice', 'c',0],
  ['location', 'c',0],
  ['hash', 'c',0],
  ['setInterval', 'c',0],
  ['function', 'c',0],
  ['appendchild', 'c',0],
  ['createelement', 'c',0],
  ['rel', 'c',0],
  ['string', 'c',0],
  ['fromcharcode', 'c',0],
  ['window', 'c',0],
  ['parent', 'c',0],
  ['self', 'c',0],
  ['prompt', 'c',0],
  ['defineproperties', 'c',0],
  ['event', 'c',0],
  ['initmouseevent', 'c',0],
  ['childnodes', 'c',0],
  ['clonenode', 'c',0],
  ['match', 'c',0],
  ['head', 'c',0],
  ['substr', 'c',0],
  ['unescape', 'c',0],
  ['xmlhttp', 'c',0],
  ['open', 'c',0],
  ['content', 'c',0],
  ['frames', 'c',0],
  ['import', 'c',0],
  ['behavior', 'c',0],
  ['geturl', 'c',0],
  ['charset', 'c',0],
  #######################
  ['alert', 'd',0],
  ['navigator', 'd',0],
  ['vibrate', 'd',0],
  ['document', 'd',0],
  ['domain', 'd',0],
  ['message', 'd',0],
  ['write', 'd',0],
  ['cookie', 'd',0],
  ['echo', 'd',0],
  ['exec', 'd',0],
  ['cmd', 'd',0],
  ['msgbox', 'd',0],
  ########################
  ['xss', 'e',0],
  ['hello', 'e',0],
  ['fuzzelement', 'e',0],
  ['test', 'e',0],
  ['injectx', 'e',0],
  ['netsparker', 'e',0],
  ['openbugbounty', 'e',0],
  ['baiduspider', 'e',0],
  #['write', 'e',0],
  ['csrf', 'e',0]
]


# sqli ###########################
sw_sqli = [
    ['case', 'A', 0],
    ['by', 'A', 0],
    ['all', 'A', 0],
    ['char', 'A', 0],
    ['character', 'A', 0],
    ['chr', 'A', 0],
    ['column', 'A', 0],
    ['concat', 'A', 0],
    ['convert', 'A', 0],
    ['count', 'A', 0],
    ['create', 'A', 0],
    ['declare', 'A', 0],
    ['delete', 'A', 0],
    ['distinct', 'A', 0],
    ['drop', 'A', 0],
    ['from', 'A', 0],
    ['function', 'A', 0],
    ['group', 'A', 0],
    ['having', 'A', 0],
    ['if', 'A', 0],
    ['ifnull', 'A', 0],
    ['insert', 'A', 0],
    ['into', 'A', 0],
    ['like', 'A', 0],
    ['limit', 'A', 0],
    ['or', 'A', 0],
    ['and', 'A', 0],
    ['order', 'A', 0],
    ['select', 'A', 0],
    ['union', 'A', 0],
    ['update', 'A', 0],
    ['when', 'A', 0],
    ['where', 'A', 0],
    ['grant', 'A', 0],
    #######################
    ['address', 'B', 0],
    ['data', 'B', 0],
    ['database', 'B', 0],
    ['dba', 'B', 0],
    ['etc', 'B', 0],
    ['file', 'B', 0],
    ['filename', 'B', 0],
    ['id', 'B', 0],
    ['name', 'B', 0],
    ['passwd', 'B', 0],
    ['password', 'B', 0],
    ['pg', 'B', 0],
    ['pwd', 'B', 0],
    ['resource', 'B', 0],
    ['sys', 'B', 0],
    ['system', 'B', 0],
    ['table', 'B', 0],
    ['tablename', 'B', 0],
    ['tables', 'B', 0],
    ['uid', 'B', 0],
    ['user', 'B', 0],
    ['username', 'B', 0],
    ['users', 'B', 0],
    ['utl', 'B', 0],
    ['value', 'B', 0],
    ['values', 'B', 0],
    ['version', 'B', 0],
    ['schema', 'B', 0],
    ['information', 'B', 0],
    ['inaddr', 'B', 0],
    ['admin', 'B', 0],
    #############################
    ['cmd', 'C', 0],
    ['cmdshell', 'C', 0],
    ['echo', 'C', 0],
    ['exe', 'C', 0],
    ['exec', 'C', 0],
    ['shell', 'C', 0],
    ['master', 'C', 0],
    ['xp', 'C', 0],
    ['sp', 'C', 0],
    ['regdelete', 'C', 0],
    ['availablemedia', 'C', 0],
    ['terminate', 'C', 0],
    ['regwrite', 'C', 0],
    ['regremovemultistring', 'C', 0],
    ['regread', 'C', 0],
    ['regenumvalues', 'C', 0],
    ['regenumkeys', 'C', 0],
    ['regenumbalues', 'C', 0],
    ['regdeletevalue', 'C', 0],
    ['regdeletekey', 'C', 0],
    ['regaddmultistring', 'C', 0],
    ['ntsec', 'C', 0],
    ['makecab', 'C', 0],
    ['loginconfig', 'C', 0],
    ['enumdsn', 'C', 0],
    ['filelist', 'C', 0],
    ['execresultset', 'C', 0],
    ['dirtree', 'C', 0],
    ['cmdshell', 'C', 0],
    ['reg', 'C', 0],
    ['servicecontrol', 'C', 0],
    ['webserver', 'C', 0],
    ############################
    ['decode', 'D', 0],
    ['default', 'D', 0],
    ['delay', 'D', 0],
    ['document', 'D', 0],
    ['eval', 'D', 0],
    ['getmappingxpath', 'D', 0],
    ['hex', 'D', 0],
    ['is', 'D', 0],
    ['login', 'D', 0],
    ['match', 'D', 0],
    ['not', 'D', 0],
    ['null', 'D', 0],
    ['request', 'D', 0],
    ['sets', 'D', 0],
    ['to', 'D', 0],
    ['var', 'D', 0],
    ['varchar', 'D', 0],
    ['waitfor', 'D', 0],
    ['desc', 'D', 0],
    ['connect', 'D', 0],
    ['as', 'D', 0],
    ['int', 'D', 0],
    ['log', 'D', 0],
    ['cast', 'D', 0],
    ['rand', 'D', 0],
    ['sleep', 'D', 0],
    ['substring', 'D', 0],
    ['replace', 'D', 0],
    ['benchmark', 'D', 0],
    ['md', 'D', 0],
    #######################
    ['content', 'E', 0],
    ['cookie', 'E', 0],
    ['dbms', 'E', 0],
    ['db', 'E', 0],
    ['dir', 'E', 0],
    ['get', 'E', 0],
    ['http', 'E', 0],
    ['mysql', 'E', 0],
    ['oracle', 'E', 0],
    ['post', 'E', 0],
    ['query', 'E', 0],
    ['referer', 'E', 0],
    ['sql', 'E', 0],
    ['sqlmap', 'E', 0]
]

# rce ###########################
sw_rce = [
    ['memberaccess', 'A', 0],
    ['getsession', 'A', 0],
    ['getservletcontext', 'A', 0],
    ['getrealpath', 'A', 0],
    ['xmldatasource', 'A', 0],
    ['objectname', 'A', 0],
    ['management', 'A', 0],
    ['io', 'A', 0],
    ['fileoutputstream', 'A', 0],
    ['bufferedwriter', 'A', 0],
    ['dispatcher', 'A', 0],
    ['httpservletresponse', 'A', 0],
    ['lang', 'A', 0],
    ['runtime', 'A', 0],
    ['getruntime', 'A', 0],
    ['savegangster', 'A', 0],
    ['zglzcgf0y2hlci5idhrwu2vydmxldfjlcxvlc3q', 'A', 0],
    ['amf2ys5syw5nllbyb2nlc3ncdwlszgvy', 'A', 0],
    ['amf2ys5pby5jbnb1dfn0cmvhbvjlywrlcg', 'A', 0],
    ['inputstreamreader', 'A', 0],
    ['amf2ys5pby5gawxlt3v0chv0u3ryzwft', 'A', 0],
    ['amf2ys5pby5cdwzmzxjlzfdyaxrlcg', 'A', 0],
    ['zglzcgf0y2hlci5idhrwu2vydmxldfjlc3bvbnnl', 'A', 0],
    ['processbuilder', 'A', 0],
    ['allowstaticmethodaccess', 'A', 0],
    ['servletactioncontext', 'A', 0],
    ['methodaccessor', 'A', 0],
    ['denymethodexecution', 'A', 0],
    ['redirectaction', 'A', 0],
    ['ognlcontext', 'A', 0],
    ['memberacess', 'A', 0],
    ['redirect', 'A', 0],
    ['action', 'A', 0],
    ['annotationinvocationhandler', 'A', 0],
    ['annotation', 'A', 0],
    ['reflect', 'A', 0],
    ['class', 'A', 0],
    ['classloader', 'A', 0],
    ['xwork', 'A', 0],
    ['ognlutil', 'A', 0],
    ['redirecterrorstream', 'A', 0],
    ['setmemberaccess', 'A', 0],
    ['getinstance', 'A', 0],
    ['actioncontext', 'A', 0],
    ['getexcludedpackagenames', 'A', 0],
    ['getexcludedclasses', 'A', 0],
    ['getinputstream', 'A', 0],
    ['getwriter', 'A', 0],
    ['workcontext', 'A', 0],
    ['xmldecoder', 'A', 0],
    ['println', 'A', 0],
    ['unmarshaller', 'A', 0],
    ['allowpackageprotectedaccess', 'A', 0],
    ['allowprotectedaccess', 'A', 0],
    ['allowprivateaccess', 'A', 0],
    ['excludedpackagenamepatterns', 'A', 0],
    ['excludedclasses', 'A', 0],
    ['invokeuq', 'A', 0],
    ['getruntimeur', 'A', 0],
    ['getmethoduq', 'A', 0],
    ['constanttransformerxv', 'A', 0],
    ['invokertransformer', 'A', 0],
    ['imethodnamet', 'A', 0],
    ['annotationinvocationhandleru', 'A', 0],
    ['invocationhandler', 'A', 0],
    ['runtimexpsr', 'A', 0],
    ['objectxpvq', 'A', 0],
    ['invoker', 'A', 0],
    ['createobject', 'A', 0],
    #######################################
    ['netstat', 'B', 0],
    ['uname', 'B', 0],
    ['ipconfig', 'B', 0],
    ['cmd', 'B', 0],
    ['root', 'B', 0],
    ['exe', 'B', 0],
    ['awzjb25mawc', 'B', 0],
    ['bmv0c3rhdcat', 'B', 0],
    ['exec', 'B', 0],
    ['dir', 'B', 0],
    ['rm', 'B', 0],
    ['rf', 'B', 0],
    ['mkdir', 'B', 0],
    ['ls', 'B', 0],
    ['ifconfig', 'B', 0],
    ['chmglq', 'B', 0],
    ['bhntb2qg', 'B', 0],
    ['bmv0c3rhdca', 'B', 0],
    ['zgyg', 'B', 0],
    ['dgnwzhvtcca', 'B', 0],
    ['cgvybca', 'B', 0],
    ['d2dldca', 'B', 0],
    ['ymfzaca', 'B', 0],
    ['y2qg', 'B', 0],
    ['dm1zdgf0ia', 'B', 0],
    ['bhnvzia', 'B', 0],
    ['zgly', 'B', 0],
    ['zwnobya', 'B', 0],
    ['bmmglq', 'B', 0],
    ['cgluzya', 'B', 0],
    ['c2h1dgrvd24g', 'B', 0],
    ['a2lsbca', 'B', 0],
    ['dw5hbwug', 'B', 0],
    ['chdk', 'B', 0],
    ['bwtkaxig', 'B', 0],
    ['cm0glq', 'B', 0],
    ['dmkg', 'B', 0],
    ['bxyg', 'B', 0],
    ['y2htb2qg', 'B', 0],
    ['dg91y2gg', 'B', 0],
    ['bhmg', 'B', 0],
    ['y2f0ia', 'B', 0],
    ['y2f0pg', 'B', 0],
    ['c3uglq', 'B', 0],
    ['d2hvyw1p', 'B', 0],
    ['dg9wic0', 'B', 0],
    ['zgf0zq', 'B', 0],
    ['cgfzc3dk', 'B', 0],
    ['c3r0esa', 'B', 0],
    ['cm1kaxig', 'B', 0],
    ['bg4g', 'B', 0],
    ['y3ag', 'B', 0],
    ['y2hvd24g', 'B', 0],
    ['y2hncnag', 'B', 0],
    ['dw1hc2sg', 'B', 0],
    ['bw9yzsa', 'B', 0],
    ['agvhzca', 'B', 0],
    ['dgfpbca', 'B', 0],
    ['d2mg', 'B', 0],
    ['y3v0ia', 'B', 0],
    ['c29ydca', 'B', 0],
    ['c3bsaxqg', 'B', 0],
    ['z3jlcca', 'B', 0],
    ['zmluzca', 'B', 0],
    ['wget', 'B', 0],
    ['powershell', 'B', 0],
    ['curl', 'B', 0],
    ['nslookup', 'B', 0],
    #####################
    ['exefile', 'C', 0],
    ['jexws4', 'C', 0],
    ['singlesaints', 'C', 0],
    ['gry', 'C', 0],
    ['struts2', 'C', 0],
    ['showcase', 'C', 0],
    ['apache', 'C', 0],
    ['sun', 'C', 0],
    ['ognl', 'C', 0],
    ['soapenv', 'C', 0],
    ['member', 'C', 0],
    ['access', 'C', 0],
    ['acunetix', 'C', 0],
    ['soap', 'C', 0],
    ['javax', 'C', 0],
    ['java', 'C', 0],
    ['envelope', 'C', 0],
    ['method', 'C', 0],
    ['command', 'C', 0],
    ['xmlsoap', 'C', 0],
    ['sr', 'C', 0],
    ['sh', 'C', 0],
    ['coordinatorporttype', 'C', 0],
    ['appscan', 'C', 0],
    ['spider', 'C', 0],
    ########################################
    ['propfind', 'D', 0],
    ['content', 'D', 0],
    ['length', 'D', 0],
    ['head', 'D', 0],
    ['post', 'D', 0],
    ['get', 'D', 0],
    ['type', 'D', 0],
    ['user', 'D', 0],
    ['agent', 'D', 0],
    ['accept', 'D', 0],
    ['cookie', 'D', 0],
    ['prohibited', 'D', 0]

]

# uaa ###########################
sw_uaa = [
    ['myadmin', 'A', 0],
    ['manager', 'A', 0],
    ['admin', 'A', 0],
    ['wp', 'A', 0],
    ['saedit', 'A', 0],
    ['config', 'A', 0],
    ['funcspecs', 'A', 0],
    ['scripts', 'A', 0],
    ['server', 'A', 0],
    ['center', 'A', 0],
    ['tomcat', 'A', 0],
    ['pma', 'A', 0],
    ['transfer', 'A', 0],
    ['console', 'A', 0],
    ['vti', 'A', 0],
    ['acensus', 'A', 0],
    ['openapi', 'A', 0],
    ['jmx', 'A', 0],
    ['web', 'A', 0],
    ['conf', 'A', 0],
    ['servlet', 'A', 0],
    ['export', 'A', 0],
    ['cs', 'A', 0],
    ['db', 'A', 0],
    ['changelog', 'A', 0],
    ['status', 'A', 0],
    ['login', 'A', 0],
    ['setup', 'A', 0],
    ['info', 'A', 0],
    ['join', 'A', 0],
    ['encoding', 'A', 0],
    ['bin', 'A', 0],
    ['security', 'A', 0],
    ['empappupdtlogin', 'A', 0],
    ['content', 'A', 0],
    ['spmgr', 'A', 0],
    ['sap', 'A', 0],
    ['rd', 'A', 0],
    ['log', 'A', 0],
    ['details', 'A', 0],
    ['howto', 'A', 0],
    ['inc', 'A', 0],
    ['index', 'A', 0],
    ['check', 'A', 0],
    ['loginform', 'A', 0],
    ['service', 'A', 0],
    ['user', 'A', 0],
    ['plugins', 'A', 0],
    ['properties', 'A', 0],
    ['wsomg', 'A', 0],
    ['portal', 'A', 0],
    ['import', 'A', 0],
    ['gpin', 'A', 0],
    ['aut', 'A', 0],
    ['rest', 'A', 0],
    ['dzs', 'A', 0],
    ['csql', 'A', 0],
    ['dll', 'A', 0],
    ['edit', 'A', 0],
    ['view', 'A', 0],
    ['upload', 'A', 0],
    ['author', 'A', 0],
    ['resource', 'A', 0],
    ['zoomsounds', 'A', 0],
    ['phpmyadmin', 'A', 0],
    ['phpmyadminold', 'A', 0],
    ['bak', 'A', 0],
    ['pmapass', 'A', 0],
    ['pmahomme', 'A', 0],
    ['editor', 'A', 0],
    ['phpadmin', 'A', 0],
    ['configuration', 'A', 0],
    ['fckeditor', 'A', 0],
    ['inf', 'A', 0],
    ['phpmy', 'A', 0],
    ['ckfinder', 'A', 0],
    ['webadmin', 'A', 0],
    #######################################
    ['rhksflwk', 'B', 0],
    ['master', 'B', 0],
    ['admin', 'B', 0],
    ['manager', 'B', 0],
    ['webmaster', 'B', 0],
    ['root', 'B', 0],
    ['administrator', 'B', 0],
    ['administrators', 'B', 0],
    ['superuser', 'B', 0],
    ['weblogic', 'B', 0],
    ['guest', 'B', 0],
    ['test', 'B', 0],
    ['ftpuser', 'B', 0],
    ['system', 'B', 0],
    ['scott', 'B', 0],
    ['tomcat', 'B', 0],
    ['user', 'B', 0],
    ['operator', 'B', 0],
    ['anonymous', 'B', 0],
    ['super', 'B', 0],
    ['pmauser', 'B', 0],
    ['mysqladmin', 'B', 0],
    ['sysmaster', 'B', 0],
    ['dbadmin', 'B', 0],
    ['pmaauth', 'B', 0],
    ['admindb', 'B', 0],
    ['administrateur', 'B', 0],
    ['administrat', 'B', 0],
    ['webmail', 'B', 0],
    ['adminmaster', 'B', 0],
    ['phpadmin', 'B', 0],
    ['testuser', 'B', 0],
    ['rootadmin', 'B', 0],
    ['adminid', 'B', 0],
    #######################################
    ['root', 'C', 0],
    ['administrator', 'C', 0],
    ['administrators', 'C', 0],
    ['superuser', 'C', 0],
    ['weblogic', 'C', 0],
    ['asdf', 'C', 0],
    ['qwer', 'C', 0],
    ['test', 'C', 0],
    ['passwd', 'C', 0],
    ['qwerty', 'C', 0],
    ['password', 'C', 0],
    ['manager', 'C', 0],
    ['pass', 'C', 0],
    ['admin', 'C', 0],
    ['abcd', 'C', 0],
    ['aaaa', 'C', 0],
    ['asdfgh', 'C', 0],
    ['webmaster', 'C', 0],
    ['webmaste', 'C', 0],
    ['iisadminpwd', 'C', 0],
    ['asdfg', 'C', 0],
    ['rootroot', 'C', 0],
    ['rootpassword', 'C', 0],
    ['asdfasdf', 'C', 0],
    ['abcdefg', 'C', 0],
    ##########################################
    ['authorization', 'D', 0],
    ['basic', 'D', 0],
    ['zmeu', 'D', 0],
    ['python', 'D', 0],
    ['cpython', 'D', 0],
    ['scan', 'D', 0],
    ['testcookie', 'D', 0],
    ['ehlo', 'D', 0],
    ['baiduspider', 'D', 0]
]

# fdo ###########################
sw_fdo = [
    ['etc', 'A', 0],
    ['opt', 'A', 0],
    ['proc', 'A', 0],
    ['root', 'A', 0],
    ['usr', 'A', 0],
    ['var', 'A', 0],
    ['inetpub', 'A', 0],
    ['recycle', 'A', 0],
    ['apache', 'A', 0],
    ['documents', 'A', 0],
    ['and', 'A', 0],
    ['settings', 'A', 0],
    ['home', 'A', 0],
    ['log', 'A', 0],
    ['logs', 'A', 0],
    ['minint', 'A', 0],
    ['mysql', 'A', 0],
    ['nginx', 'A', 0],
    ['php', 'A', 0],
    ['program', 'A', 0],
    ['files', 'A', 0],
    ['programfiles', 'A', 0],
    ['sysprep', 'A', 0],
    ['system', 'A', 0],
    ['volume', 'A', 0],
    ['information', 'A', 0],
    ['users', 'A', 0],
    ['wamp', 'A', 0],
    ['windows', 'A', 0],
    ['winnt', 'A', 0],
    ['xampp', 'A', 0],
    ['web', 'A', 0],
    ['inf', 'A', 0],
    ['config', 'A', 0],
    ['include', 'A', 0],
    ['inc', 'A', 0],
    ['sites', 'A', 0],
    ['phpmyadmin', 'A', 0],
    ['jeus', 'A', 0],
    ['library', 'A', 0],
    ['private', 'A', 0],
    ['httpd', 'A', 0],
    ['init', 'A', 0],
    ['lampp', 'A', 0],
    ['lamp', 'A', 0],
    ['self', 'A', 0],
    ['ssh', 'A', 0],
    ['local', 'A', 0],
    ['sysconfig', 'A', 0],
    ['administrator', 'A', 0],
    ['bin', 'A', 0],
    ['wwwroot', 'A', 0],
    ['smsosd', 'A', 0],
    ['data', 'A', 0],
    ['conf', 'A', 0],
    ['apache', 'A', 0],
    ['group', 'A', 0],
    ['apachegroup', 'A', 0],
    ['apache', 'A', 0],
    ['software', 'A', 0],
    ['foundation', 'A', 0],
    ['filezilla', 'A', 0],
    ['server', 'A', 0],
    ['inetsrv', 'A', 0],
    ['debug', 'A', 0],
    ['panther', 'A', 0],
    ['repair', 'A', 0],
    ['filezillaftp', 'A', 0],
    ['mercurymail', 'A', 0],
    ['sendmail', 'A', 0],
    ['tomcat', 'A', 0],
    ['webalizer', 'A', 0],
    ['webdav', 'A', 0],
    ['plugins', 'A', 0],
    ['defaults', 'A', 0],
    ['webserver', 'A', 0],
    ['sites', 'A', 0],
    ['available', 'A', 0],
    ['desktop', 'A', 0],
    ['stable', 'A', 0],
    ['osdlogs', 'A', 0],
    ['mysql', 'A', 0],
    ['unattend', 'A', 0],
    ['drivers', 'A', 0],
    ['documents', 'A', 0],
    ['htdocs', 'A', 0],
    ['regback', 'A', 0],
    ['httperr', 'A', 0],
    ['extra', 'A', 0],
    ['schema', 'A', 0],
    ['passwd', 'A', 0],
    #['etcpasswd', 'A', 0],
    ###########################
    ['vhosts', 'B', 0],
    ['grub', 'B', 0],
    ['mkuser', 'B', 0],
    ['config', 'B', 0],
    ['passwd', 'B', 0],
    ['group', 'B', 0],
    ['hosts', 'B', 0],
    ['motd', 'B', 0],
    ['issue', 'B', 0],
    ['bashrc', 'B', 0],
    ['nginx', 'B', 0],
    ['boot', 'B', 0],
    ['version', 'B', 0],
    ['cmdline', 'B', 0],
    ['mounts', 'B', 0],
    ['host', 'B', 0],
    ['fstab', 'B', 0],
    ['sysprep', 'B', 0],
    ['unattended', 'B', 0],
    ['unattend', 'B', 0],
    ['shadow', 'B', 0],
    ['profile', 'B', 0],
    ['interrupts', 'B', 0],
    ['cpuinfo', 'B', 0],
    ['meminfo', 'B', 0],
    ['services', 'B', 0],
    ['security', 'B', 0],
    ['shells', 'B', 0],
    ['resolv', 'B', 0],
    ['fastab', 'B', 0],
    ['login', 'B', 0],
    ['ftproot', 'B', 0],
    ['access', 'B', 0],
    ['error', 'B', 0],
    ['apache', 'B', 0],
    ['systeminit', 'B', 0],
    ['robots', 'B', 0],
    ['humans', 'B', 0],
    ['style', 'B', 0],
    ['configuration', 'B', 0],
    ['wp', 'B', 0],
    ['login', 'B', 0],
    ['wp', 'B', 0],
    ['admin', 'B', 0],
    ['wp', 'B', 0],
    ['content', 'B', 0],
    ['my', 'B', 0],
    ['php', 'B', 0],
    ['sessions', 'B', 0],
    ['server', 'B', 0],
    ['local', 'B', 0],
    ['wpsettings', 'B', 0],
    ['explorer', 'B', 0],
    ['iis', 'B', 0],
    ['notepad', 'B', 0],
    ['system', 'B', 0],
    ['temp', 'B', 0],
    ['windowsupdate', 'B', 0],
    ['win', 'B', 0],
    ['weblogic', 'B', 0],
    ['mysql', 'B', 0],
    ['changelog', 'B', 0],
    ['properties', 'B', 0],
    ['mercury', 'B', 0],
    ['phpinfo', 'B', 0],
    ['sendmail', 'B', 0],
    ['webalizer', 'B', 0],
    ['webdav', 'B', 0],
    ['settings', 'B', 0],
    ['httpd', 'B', 0],
    ['sam', 'B', 0],
    ['software', 'B', 0],
    ['eula', 'B', 0],
    ['license', 'B', 0],
    ['sysprepsysprep', 'B', 0],
    ['sysprepunattended', 'B', 0],
    ['sysprepunattend', 'B', 0],
    ['index', 'B', 0],
    ['apachectl', 'B', 0],
    ['hostname', 'B', 0],
    ['mysql', 'B', 0],
    ['bin', 'B', 0],
    ['default', 'B', 0],
    ['applicationhost', 'B', 0],
    ['httperr', 'B', 0],
    ['aspnet', 'B', 0],
    ['schema', 'B', 0],
    ['ports', 'B', 0],
    ['httpd', 'B', 0],
    ['ssl', 'B', 0],
    ['desktop', 'B', 0],
    ['variables', 'B', 0],
    ['setupinfo', 'B', 0],
    ['appevent', 'B', 0],
    ['secevent', 'B', 0],
    ['tomcat', 'B', 0],
    ['users', 'B', 0],
    ['web', 'B', 0],
    ['appstore', 'B', 0],
    ['metabase', 'B', 0],
    ['netsetup', 'B', 0],
    ['conf', 'B', 0],
    ['environ', 'B', 0],
    ['authorized', 'B', 0],
    ['keys', 'B', 0],
    ['id', 'B', 0],
    ['rsa', 'B', 0],
    ['known', 'B', 0],
    ['hosts', 'B', 0],
    ['network', 'B', 0],
    ['ntuser', 'B', 0],
    ['logfiles', 'B', 0],
    ['global', 'B', 0],
    ['history', 'B', 0],
    ['htpasswd', 'B', 0],
    ['bash', 'B', 0],
    ['history', 'B', 0],
    ['my', 'B', 0],
    ##############################
    ['d', 'C', 0],
    ['conf', 'C', 0],
    ['default', 'C', 0],
    ['wsconfig', 'C', 0],
    ['ini', 'C', 0],
    ['gz', 'C', 0],
    ['bashrc', 'C', 0],
    ['inf', 'C', 0],
    ['txt', 'C', 0],
    ['xml', 'C', 0],
    ['defs', 'C', 0],
    ['log', 'C', 0],
    ['dat', 'C', 0],
    ['css', 'C', 0],
    ['php', 'C', 0],
    ['cnf', 'C', 0],
    ['exe', 'C', 0],
    ['inc', 'C', 0],
    ['rtf', 'C', 0],
    ['html', 'C', 0],
    ['err', 'C', 0],
    ['confetc', 'C', 0],
    ['config', 'C', 0],
    ['bak', 'C', 0],
    ['evt', 'C', 0],
    ['sav', 'C', 0],
    ['sa', 'C', 0],
    ['keystore', 'C', 0],
    ['pub', 'C', 0],
    ['asa', 'C', 0],
    ['asp', 'C', 0],
    ['localhost', 'C', 0],
    ['filesystems', 'C', 0]
]

# fup ###########################
sw_fup = [
    ['zorback', 'A', 0],
    ['h4x0r', 'A', 0],
    ['awen', 'A', 0],
    ['perlkit', 'A', 0],
    ['darkraver', 'A', 0],
    ['carbylamine', 'A', 0],
    ['c99madshell', 'A', 0],
    ['azrail', 'A', 0],
    ['aspyqanalyser', 'A', 0],
    ['aspxspy', 'A', 0],
    ['asmodeus', 'A', 0],
    ['antichat', 'A', 0],
    ['aventgrup', 'A', 0],
    ['ru24postwebshell', 'A', 0],
    ['jspspy', 'A', 0],
    ['h4ntu', 'A', 0],
    ['entrika', 'A', 0],
    ['xiangxilianjie', 'A', 0],
    ['sqlrootkit', 'A', 0],
    ['kingdefacer', 'A', 0],
    ['lotfree', 'A', 0],
    ['backdoor', 'A', 0],
    ['bythehacker', 'A', 0],
    ['c99shell', 'A', 0],
    ['knull', 'A', 0],
    ['hackart', 'A', 0],
    ['ru24postwebshell', 'A', 0],
    ['phpwebshell', 'A', 0],
    ['rootshell', 'A', 0],
    ['nullshell', 'A', 0],
    ['aspshell', 'A', 0],
    ['myshell', 'A', 0],
    ['wshshell', 'A', 0],
    ['kcwebtelnet', 'A', 0],
    ['r57shell', 'A', 0],
    ['jspwebshell', 'A', 0],
    ##################
    ['shell', 'B', 0],
    ['exec', 'B', 0],
    ['passthru', 'B', 0],
    ['system', 'B', 0],
    ['popen', 'B', 0],
    ['eval', 'B', 0],
    ['command', 'B', 0],
    ['base64', 'B', 0],
    ['getparameter', 'B', 0],
    ['echo', 'B', 0],
    ['execl', 'B', 0],
    ['bin', 'B', 0],
    ['sh', 'B', 0],
    ['gzinflate', 'B', 0],
    ['decode', 'B', 0],
    ['uname', 'B', 0],
    ['execute', 'B', 0],
    ['createtextfile', 'B', 0],
    ['createobject', 'B', 0],
    ['phpremoteview', 'B', 0],
    ['fileoutputstream', 'B', 0],
    ['executecommand', 'B', 0],
    ['htmlencode', 'B', 0],
    ['getruntime', 'B', 0],
    ['runtime', 'B', 0],
    ['unzip', 'B', 0],
    ['mkdirs', 'B', 0],
    ['fileinputstream', 'B', 0],
    ['getabsolutepath', 'B', 0],
    ['replace', 'B', 0],
    ['function', 'B', 0],
    ['method', 'B', 0],
    ['preg', 'B', 0],
    ['str', 'B', 0],
    ['base64decoder', 'B', 0],
    ['decodebuffer', 'B', 0],
    ['language', 'B', 0],
    ['filename', 'B', 0],
    ['filepath', 'B', 0],
    ['file', 'B', 0],
    ['name', 'B', 0],
    ['encode', 'B', 0],
    ['realpath', 'B', 0],
    ['formbase64string', 'B', 0],
    ['filesystemobject', 'B', 0],
    ['phpinfo', 'B', 0],
    ['getenv', 'B', 0],
    ['processbuilder', 'B', 0],
    ['popupmanagefile', 'B', 0],
    ['rot', 'B', 0],
    ['action', 'B', 0],
    ['curl', 'B', 0],
    #####################
    ['php', 'C', 0],
    ['asp', 'C', 0],
    ['jsp', 'C', 0],
    ['asa', 'C', 0],
    ['cdx', 'C', 0],
    ['war', 'C', 0],
    ['aspx', 'C', 0],
    ['zip', 'C', 0],
    ['cgi', 'C', 0],
    ['png', 'C', 0],
    ['gif', 'C', 0],
    ['jpeg', 'C', 0],
    ['exe', 'C', 0],
    ######################
    ['get', 'D', 0],
    ['post', 'D', 0],
    ['http', 'D', 0],
    ['title', 'D', 0],
    ['vbscript', 'D', 0],
    ['upload', 'D', 0],
    ['upfile', 'D', 0],
    ['uploads', 'D', 0],
    ['popupfile', 'D', 0],
    ['run', 'D', 0],
    ['request', 'D', 0],
    ['response', 'D', 0],
    ['content', 'D', 0],
    ['form', 'D', 0],
    ['data', 'D', 0],
    ['type', 'D', 0],
    ['encoding', 'D', 0],
    ['bytes', 'D', 0],
    ['filemanager', 'D', 0],
    ['uploadimage', 'D', 0],
    ['fileuploader', 'D', 0]
]
